---
title: "a selection of past projects and published work"
---

```{css, echo = FALSE}
*
body{
  font-family: "Courier New";
  font-size: small;
}
```

<br/>

## **climate finance and policy**

this is mostly what i do :)

<br/>

#### Public Development Banks' Climate Commitments: 2024

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/publication/public-development-banks-climate-commitments-2024/)

**Chin, N.**, Schell-Smith, K., Feng, Y. (2024)

<br/>

#### Building AI/ML Tools to Track Public Development Banks' Climate Ambition

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/building-al-ml-tools-to-track-public-development-banks-climate-ambition/)

**Chin, N.** & Vo, D. (2024)

<br/>

#### Resilient Municipal Market Fund

[Global Innovation Lab for Climate Finance](https://www.climatefinancelab.org/ideas/resilient-municipal-market-fund-remark/)

Richmond, M., Lee, M., **Chin, N.**, Nirula, A. (2024)

<br/>

#### Tracking and Mobilizing Private Sector Climate Adaptation Finance

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/publication/tracking-and-mobilizing-private-sector-climate-adaptation-finance/)

Connolly, J., Richmond, M., Wallock, W., Abraham, S., **Chin, N.**, Grant, C. (2024)

<br/>

#### Approaches to Meeting the Paris Agreement Goals: Options for PDBs

[Climate Policy Initiative & I4CE](https://www.climatepolicyinitiative.org/publication/approaches-to-meeting-the-paris-agreement-goals/)

**Chin, N.**, Pinko, N., Olutoke, J., Eschalier, C., Zamarioli Santos, L., Bendahou, S. (2024)

<br/>

#### Public Financial Institutions' Climate Commitments: 2023 Update

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/publication/public-financial-institutions-climate-commitments-2023-update/)

**Chin, N.**, Schell-Smith, K., Pinko, N. (2024)

<br/>

#### Enhancing MDB-NDB Cooperation
[Climate Policy Initiative & E3G](https://www.climatepolicyinitiative.org/publication/enhancing-mdb-ndb-cooperation-understanding-climate-finance-flows-and-paris-alignment/)

Ahlgren, V., Sabogal, L., **Chin, N.**, Bagnera, E., Pinko, N. (2023)

<br/>

#### Accelerating Urban Climate Finance in Low- and Middle-Income Countries
[Cities Climate Finance Leadership Alliance](https://citiesclimatefinance.org/publications/accelerating-urban-climate-finance-in-low-and-middle-income-countries/)

Negrieros, P., Bagnera, E., Abdullah, H., La Salle, J.M., **Chin, N.**, Vieira, A., Tonkonogy, B. (2023)

<br/>

#### How Do Countries Talk About Climate Action?
[Graduate School Project](files/TAD_final_project.pdf)

**Chin, N.** (2023)

<br/>

#### Public Financial Institutions' Climate Commitments

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/publication/public-financial-institutions-climate-commitments/)

Ortega Pastor, A., Pinko, N., **Chin, N.**, & Tonkonogy, B. (2022)

<br/>

#### Financial Innovation for Climate Adaptation in Africa

[Global Center on Adaptation (authored by Climate Policy Initiative)](https://gca.org/wp-content/uploads/2022/08/GCA-Financial-Innovation-for-Climate-Adaptation-in-Africa-2022.pdf)

Richmond, M., Tonkonogy, B., Padmanabhi, R., Ortega Pastor, A., **Chin, N.**, & Hebbale, C. (2022)

<br/>

#### Why the First Global Stocktake Should Not Overlook Long-Term Climate Strategies

[World Resources Institute: Insights](https://www.wri.org/insights/why-first-global-stocktake-should-not-overlook-long-term-climate-strategies)

**Chin, N.** & Elliott, C. (2021)

<br/>

#### The State and Effectiveness of the Green Bond Market in China

[Climate Policy Initiative](https://www.climatepolicyinitiative.org/publication/green-bonds-in-china-the-state-and-effectiveness-of-the-market/)

Escalante, D., Choi, J., & **Chin, N**. (2020)

<br/>

## **other projects**

i sometimes do research work outside of my primary field — where i lack expertise i try to make up for it with curiosity!

<br/>

#### Why Majors Matter: Occupation Specificity, Job Skills, and College Selectivity

[Contemporary Economic Policy](https://onlinelibrary.wiley.com/doi/10.1111/coep.12634)

Weiss, D., Spitzer, M., Cronin, C., & **Chin, N.** (2023)

<br/>

#### Did Medicaid Expansion Change the Trajectory of Drug Overdose Deaths in Appalachia?

[Graduate School Project](files/U6614_final_project.pdf)

**Chin, N.** & Wu, Y. (2022)

R code available on [Github](https://github.com/nkc98/U6614_final_project/blob/main/project_document.Rmd).

<br/>

#### Our Global Health Frameworks in COVID-19: Who Was Left Behind?

[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4283349)

**Chin, N.,** Dasaraju, S., Nair-Desai, S., & Nambiar, K. (2022)


